spring:
    application:
        name: gatewayserver
    config:
        import: optional:configserver:http://localhost:8888
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: false
                    lower-case-service-id: true
