spring:
    application:
        name: gatewayserver
    profiles:
        active: dev
    config:
        import: "optional:configserver:http://localhost:8888/"
        #import: "optional:configserver:http://configserver-ms:8888/"
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: false
                    lower-case-service-id: true
    main:
        #web-application-type: reactive
        allow-bean-definition-overriding: true


logging:
    level:
        org.springframework.cloud.gateway: DEBUG
        org.springframework.web: ERROR
        reactor.netty: DEBUG

##springdoc:
    ##group-configs:
      ##  0:
        ##    group: "default"
          ##  display-name: "Default"
          ##  paths-to-match: "/tfg/inventario/v3/api-docs"
        
      ##  1:
        ##    group: "admin"
          ##  display-name: "Admin"
          ##  paths-to-match: "/admin/**"
springdoc:
  enable-native-support: true
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: "inventario"
      display-name: "Inventario"
      paths-to-match: "/tfg/inventario/**"  # Asegúrate de que coincida con la ruta en el Gateway
    - group: "reservas"
      display-name: "Reservas"
      paths-to-match: "/tfg/reservas/**"
    - group: "pagos"
      display-name: "Pagos"
      paths-to-match: "/tfg/pagos/**"
    - group: "gps"
      display-name: "GPS"
      paths-to-match: "/tfg/gps/**"
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Inventario
        url: /tfg/inventario/v3/api-docs  # Esta URL debe redirigir al servicio de inventario
      - name: Reservas
        url: /tfg/reservas/v3/api-docs  # Esta URL debe redirigir al servicio de reservas
      - name: Pagos
        url: /tfg/pagos/v3/api-docs      # Esta URL debe redirigir al servicio de pagos
      - name: GPS
        url: /tfg/gps/v3/api-docs        # Esta URL debe redirigir al servicio de GPS

            
            


                
    
    
                        
            
