server:
    port: 8888

spring:
    application:
        name: "configserver"
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/datalbert/trabajotfgconfiguraciones.git
                    clone-on-start: true
                    force-pull: true
                    timeout: 10
                    default-label: main
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state: 
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
    key: GqJRUuNdYp



