spring:
    application:
        name: pago
    profiles:
        active:
            - default
    config:
        import: "optional:configserver:http://configserver-container:8888/"
    

paypal:
    mode: sandbox
    client-id: AeztPFCVfz11CMp2HZTpjH_WvwiGfyyjQqyoiTW-pN1PucqqmHM4lEhyguTfFiOc9DXwDenCZn9D_rv4
    client-secret: ECof2AOBm33P04kw1vC8O6HqR2V6qSST-SYXWJg2uyH0rt6KGaT24wMIT33U4_aq4sn2qDhdZUwHEV0V



