spring:
    application:
        name: reservas
    profiles:
        active:
            - default
    
    config:
        import: "optional:configserver:http://configserver-container:8888/"
        #import: "optional:configserver:http://localhost:8888/"

    





