spring:
  application:
      name: inventario
  profiles:
      active: dev
  config:
        #import: "optional:configserver:http://configserver-ms:8888/"
        import: "optional:configserver:http://localhost:8888/"

#eureka:
 # instance:
  #  preferIpAddress: true
  #client:
   # fetchRegistry: true
    #registerWithEureka: true
    #serviceUrl:
        #defaultZone: http://eurekaserver-ms:8070/eureka/
     #   defulttZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate: 
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    
                       
