spring:
    application:
        name: gps
    config:
        import: "optional:configserver:http://localhost:8888/"


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
        defaultZone: http://localhost:8070/eureka/



management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate: 
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true