spring:
    application:
        name: "usuarios"
    config:
        import: "optional:configserver:http://localhost:8888/"
    datasource:
        url: jdbc:mysql://localhost:3306/usuariosdb
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
        defaultZone: http://localhost:8070/eureka/






